"""Independent policy baselines and real Git behavior for managed paths."""

from app import app_apply, app_git, install
from app import managed_paths as mp

# --- Independent baseline: the exact .gitignore body, line by line -----------
_EXPECTED_GITIGNORE_LINES = [
  "# Generated build output and vendored deps are not hand-written source.",
  "dist/",
  ".build/",
  "node_modules/",
  "# Python app jobs compile beside source; bytecode is runtime cache, not source.",
  "__pycache__/",
  "*.py[cod]",
  ".pytest_cache/",
  ".mypy_cache/",
  ".ruff_cache/",
  ".coverage",
  "htmlcov/",
  "# Local diagnostics, editor residue, and machine-specific secrets are not source.",
  "*.log",
  ".DS_Store",
  "*.swp",
  "*.swo",
  "*~",
  ".env",
  ".env.local",
  ".env.*.local",
  ".build-*/",
  "# Manifest static_assets are install-managed (re-fetched from the manifest,",
  "# tracked in .mobius-static-assets.json), not edited source — keep runtime",
  "# bundles/binaries out of history while admitting Store listing media through",
  "# the one author-owned subtree reserved by the manifest contract.",
  "static/*",
  "!static/store/",
  "!static/store/**",
  ".mobius-static-assets.json",
  "# Install/rollback snapshots are not source.",
  "*.bak",
  "*.mobius-bak",
  "*.mobius-drop-bak",
  "# init-cron.sh is install-managed (re-generated by the scaffold on every",
  "# update that declares a schedule, dropped by _drop_app_cron when one is",
  "# removed). It must NOT be tracked: tracking it lets a later merge-abort or",
  "# conflict hard-reset restore a dropped script, which the entrypoint boot",
  "# replay then re-arms as an orphan cron.",
  "init-cron.sh",
  "init-cron.sh.tombstoned",
  ".cron-pending.json",
  "# Runtime workspaces staged by scheduled/background apps are not source.",
  "inputs/",
  "runs/",
  "settings.json",
  "last-run.json",
  "reflection-brief-template.html",
  "fork-chat.sh",
  "fork-session.sh",
  "# Defensive: the integer-id storage tree is a sibling dir, but if a",
  "# numeric data dir ever lands here it is runtime data, not source.",
  "[0-9]*/",
]
_EXPECTED_GITIGNORE = "\n".join(_EXPECTED_GITIGNORE_LINES + [""])

# --- Independent baseline: the exact untrack pathspec set (order irrelevant) --
_EXPECTED_RUNTIME_PATHSPECS = {
  ".mobius-static-assets.json",
  "*.bak",
  "*.mobius-bak",
  "*.mobius-drop-bak",
  ":(glob)**/*.bak",
  ":(glob)**/*.mobius-bak",
  ":(glob)**/*.mobius-drop-bak",
  "init-cron.sh",
  "init-cron.sh.tombstoned",
  ".cron-pending.json",
  "inputs",
  "runs",
  "settings.json",
  "last-run.json",
  "reflection-brief-template.html",
  "fork-chat.sh",
  "fork-session.sh",
  ":(glob)**/__pycache__/**",
  ":(glob)**/*.py[cod]",
  ":(glob)**/.pytest_cache/**",
  ":(glob)**/.mypy_cache/**",
  ":(glob)**/.ruff_cache/**",
  ":(glob)**/.coverage",
  ":(glob)**/htmlcov/**",
  ":(glob)**/*.log",
  ":(glob)**/.DS_Store",
  ":(glob)**/*.swp",
  ":(glob)**/*.swo",
  ":(glob)**/*~",
  ":(glob)**/.env",
  ":(glob)**/.env.local",
  ":(glob)**/.env.*.local",
  ":(glob)**/.build-*/**",
}

_EXPECTED_MERGED_NON_SOURCE = frozenset(
  {".gitignore", ".mobius-static-assets.json", "init-cron.sh"}
)


def test_gitignore_body_is_byte_identical_to_baseline():
  """Preserve comment/order stability and the trailing newline in exclude blocks."""
  assert mp.GITIGNORE == _EXPECTED_GITIGNORE


def test_untrack_pathspecs_match_baseline_membership_without_duplicates():
  """Order is irrelevant to `git rm --cached`, but the exact set and count must
  hold — no dropped selector, no accidental duplicate."""
  assert set(mp.MANAGED_RUNTIME_PATHS) == _EXPECTED_RUNTIME_PATHSPECS
  assert len(mp.MANAGED_RUNTIME_PATHS) == len(_EXPECTED_RUNTIME_PATHSPECS)


def test_merged_non_source_matches_baseline():
  """Merged-tree drop set is exact literal names (not globs/basenames)."""
  assert mp.MERGED_NON_SOURCE == _EXPECTED_MERGED_NON_SOURCE


def test_consumers_use_the_derived_registry_values():
  """The git layer and installer must read the registry, not a stale parallel
  copy — this is what keeps the three views from drifting apart again."""
  assert app_git._GITIGNORE is mp.GITIGNORE
  assert app_git._MANAGED_RUNTIME_PATHS is mp.MANAGED_RUNTIME_PATHS
  assert install._MERGED_NON_SOURCE is mp.MERGED_NON_SOURCE
  assert install._STATIC_ASSETS_MANIFEST == mp.STATIC_ASSETS_MANIFEST
  assert app_apply._STATIC_ASSETS_MANIFEST == mp.STATIC_ASSETS_MANIFEST


def test_static_assets_manifest_constant_is_single_sourced():
  assert mp.STATIC_ASSETS_MANIFEST == ".mobius-static-assets.json"


def test_reordered_untrack_selectors_preserve_source_and_runtime_files(tmp_path):
  repo = tmp_path / "app"
  repo.mkdir()
  app_git._run(repo, "init", "-q")
  runtime = {
    ".mobius-static-assets.json", "init-cron.sh", "init-cron.sh.tombstoned",
    ".cron-pending.json", "inputs/job.json", "runs/job/result.json",
    "settings.json", "last-run.json", "reflection-brief-template.html",
    "fork-chat.sh", "fork-session.sh", "index.jsx.bak",
    "nested/index.jsx.mobius-bak", "deep/nested/job.mobius-drop-bak",
    "__pycache__/job.pyc", "nested/__pycache__/job.pyc", "job.pyo",
    "nested/job.pyd", ".pytest_cache/state", "nested/.mypy_cache/state",
    "nested/.ruff_cache/state", ".coverage", "nested/.coverage",
    "htmlcov/index.html", "nested/htmlcov/index.html", "debug.log",
    "nested/debug.log", ".DS_Store", "nested/.DS_Store", "file.swp",
    "nested/file.swo", "file~", ".env", "nested/.env.local",
    "nested/.env.test.local", ".build-preview/bundle.js",
    "nested/.build-preview/bundle.js",
  }
  source = {
    "index.jsx", "helpers.js", "nested/util.ts", "mobius.json",
    "static/store/cover.png",
  }
  # Ignore-only policies do not retroactively untrack existing files.
  ignored_but_tracked = {
    "dist/app.js", "static/app.js", "12/data.json",
    "nested/init-cron.sh", "nested/settings.json",
  }
  paths = runtime | source | ignored_but_tracked
  for rel in paths:
    path = repo / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("fixture\n", encoding="utf-8")
  app_git._run(repo, "add", "--", ".")
  baseline = app_git._run(
    repo, "ls-files", "--", *sorted(_EXPECTED_RUNTIME_PATHSPECS),
  ).stdout.splitlines()
  derived = app_git._run(
    repo, "ls-files", "--", *mp.MANAGED_RUNTIME_PATHS,
  ).stdout.splitlines()
  assert set(derived) == set(baseline) == runtime

  app_git._refresh_ignore_rules(repo)

  assert set(app_git._run(repo, "ls-files").stdout.splitlines()) == (
    source | ignored_but_tracked
  )
  assert all((repo / rel).read_text(encoding="utf-8") == "fixture\n" for rel in paths)
  ignored = app_git._run(
    repo, "check-ignore", "--no-index", "--", *sorted(paths),
  ).stdout.splitlines()
  assert "static/app.js" in ignored
  assert "static/store/cover.png" not in ignored
  assert "helpers.js" not in ignored
