import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { rolldown } from 'rolldown'

const frontendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = path.join(frontendDir, 'public', 'mobius-runtime.js')

const bundle = await rolldown({
  cwd: frontendDir,
  input: 'src/runtime/index.js',
  platform: 'browser',
  tsconfig: false,
  transform: { target: 'es2022' },
})

let result
try {
  result = await bundle.generate({
    format: 'es',
    codeSplitting: false,
    comments: { legal: true },
    banner: '// GENERATED by scripts/build-runtime.mjs from src/runtime/. Do not edit this file directly.',
    minify: false,
    sourcemap: false,
  })
} finally {
  await bundle.close()
}

const chunks = result.output.filter((item) => item.type === 'chunk')
const entry = chunks.find((item) => item.isEntry)
if (!entry || chunks.length !== 1 || result.output.length !== 1) {
  throw new Error('Rolldown did not produce one mini-app runtime module')
}
const output = Buffer.from(entry.code)

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath) : null
  if (!current || !current.equals(output)) {
    console.error(
      'public/mobius-runtime.js is stale; run `npm run runtime:build`.',
    )
    process.exitCode = 1
  }
} else {
  fs.writeFileSync(outputPath, output)
}
