import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { rolldown } from 'rolldown'
import { enterBuildAdmission } from './build-admission.mjs'


enterBuildAdmission()

const frontendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// Root-level browser modules built from src/ and checked in beside the other
// public/ assets. Vite copies them verbatim into dist/, so each is served at
// `/<output name>` by the same static path as every other public/ file.
const BUNDLES = [
  { input: 'src/runtime/index.js', output: 'public/mobius-runtime.js', label: 'mini-app runtime' },
  { input: 'src/publicHost/index.js', output: 'public/mobius-public-host.js', label: 'public app host' },
]

async function buildBundle({ input, output, label }) {
  const bundle = await rolldown({
    cwd: frontendDir,
    input,
    platform: 'browser',
    tsconfig: false,
    transform: { target: 'es2022' },
  })
  let result
  try {
    result = await bundle.generate({
      format: 'es',
      codeSplitting: false,
      comments: { legal: true },
      banner: `// GENERATED by scripts/build-runtime.mjs from ${path.posix.dirname(input)}/. Do not edit this file directly.`,
      minify: false,
      sourcemap: false,
    })
  } finally {
    await bundle.close()
  }
  const chunks = result.output.filter((item) => item.type === 'chunk')
  const entry = chunks.find((item) => item.isEntry)
  if (!entry || chunks.length !== 1 || result.output.length !== 1) {
    throw new Error(`Rolldown did not produce one ${label} module`)
  }
  return Buffer.from(entry.code)
}

const check = process.argv.includes('--check')
for (const bundle of BUNDLES) {
  const outputPath = path.join(frontendDir, bundle.output)
  const built = await buildBundle(bundle)
  if (!check) {
    fs.writeFileSync(outputPath, built)
    continue
  }
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath) : null
  if (!current || !current.equals(built)) {
    console.error(`${bundle.output} is stale; run \`npm run runtime:build\`.`)
    process.exitCode = 1
  }
}
