import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { build } from 'esbuild'

const frontendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = path.join(frontendDir, 'public', 'mobius-runtime.js')

const result = await build({
  entryPoints: [path.join(frontendDir, 'src', 'runtime', 'index.js')],
  outfile: outputPath,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  charset: 'utf8',
  legalComments: 'inline',
  minify: false,
  sourcemap: false,
  write: false,
  banner: {
    js: '// GENERATED by scripts/build-runtime.mjs from src/runtime/. Do not edit this file directly.',
  },
})

const output = result.outputFiles?.[0]?.contents
if (!output) throw new Error('esbuild did not produce the mini-app runtime')

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath) : null
  if (!current || !current.equals(output)) {
    console.error(
      'public/mobius-runtime.js is stale; run `npm run runtime:build`.',
    )
    process.exitCode = 1
  }
} else {
  fs.writeFileSync(outputPath, output)
}
