"""Per-app git repo: pristine `upstream` history + a local working branch.

Each installed app gets its own git repo at `/data/apps/<slug>/.git` with
two branches:

  - `upstream` holds the exact bytes of each installed manifest version.
    Only the installer commits here, via `record_upstream`. It is the
    merge base that lets an update tell "did the user diverge from what
    upstream shipped" without guessing from a sha.
  - `main` is the local working branch. The file watcher and the agent
    commit their edits here (via `commit_local`); it is the branch the
    working tree actually checks out.

Update is `record_upstream` (commit the new upstream source TREE) then
`merge_upstream`, which computes a clean-vs-conflict verdict with
`git merge-tree --write-tree` WITHOUT touching the live working tree —
so a conflict never leaves the app served in a half-merged state. The
caller (install.py) applies a clean merge by reading the whole merged tree
(`read_merged_tree`), writing it back, and recompiling; on conflict it
surfaces the conflicting paths and leaves the local edits intact for an
agent to resolve later. One and many files share one tree path — the entry
`index.jsx` is just one key in the tree.

A finalized update is a SINGLE-parent replay (linear): both the clean
apply (`commit_replay`) and a resolved conflict (`commit_local` with
MERGE_HEAD set) commit the applied tree with `upstream` as its sole
parent, squashing the local delta into one replay commit on top of
upstream. So `main` is a straight-line descendant of `upstream`
(`A -> B -> X`) and `git merge-base --is-ancestor upstream main` is
exact — never the 2-parent merge a `git merge` would leave.

Only SOURCE is tracked — `index.jsx`, job scripts (`*.sh`), prompts,
seed templates. The compiled bundle (`/data/compiled/app-<id>.js`) is a
gitignored build artifact, and the integer-id storage tree
(`/data/apps/<id>/`) is a SEPARATE directory the mini-app writes at
runtime, not under this source dir at all. A committed `.gitignore`
keeps both out even if a future caller drops them here.

Why shell out to the container's `git` rather than pygit2: `git` 2.x is
already in the image, the operations are coarse-grained (one subprocess
per install/update, not a hot loop), and `merge-tree --write-tree` — the
primitive that makes the no-clobber verdict possible — is a porcelain we
get for free without a libgit2 binding to pin and maintain.

CONCURRENCY: callers MUST hold `fs_locks.source_dir_lock(<source_dir>)`
around every entry point here, so the watcher's commit-on-save can't race
the installer's merge on the same repo. This module does not take the
lock itself — the lock is keyed on the source dir, which only the caller
knows, and nesting lock acquisition inside would hide the ordering the
rest of install.py reasons about.

install.py drives this module for every app that has a source directory; an
app with no source_dir has no `.git`.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

# Branch names. `upstream` is installer-only pristine history; `main` is
# the local working branch the watcher/agent commit to and the working
# tree checks out.
UPSTREAM_BRANCH = "upstream"
LOCAL_BRANCH = "main"

# Files we never want in app source history regardless of who drops them
# in the source dir. The live compiled bundle is /data/compiled/app-<id>.js
# (outside this tree), so it never appears here. We must NOT blanket-ignore
# `*.js`: building-apps.md tells the agent to split larger apps into sibling
# `.js`/`.jsx`/`.ts`/`.tsx` modules (e.g. `cards.js`) imported from index.jsx,
# and those ARE hand-written source — a blanket `*.js` silently dropped them
# from per-app history, breaking the merge/conflict-resolution model for any
# modular app. So the ignore is scoped to genuine generated/vendored output
# (mirrors the watcher's recompile-ignore set) plus install artifacts and the
# integer-id storage tree.
_GITIGNORE = "\n".join([
  "# Generated build output and vendored deps are not hand-written source.",
  "dist/",
  ".build/",
  "node_modules/",
  "# Manifest static_assets are install-managed (re-fetched from the manifest,",
  "# listed in .mobius-static-assets.json), not edited source — keep prebuilt",
  "# bundles/binaries out of per-app history.",
  "static/",
  "# Install/rollback snapshots are not source.",
  "*.bak",
  "*.mobius-bak",
  "# init-cron.sh is install-managed (re-generated by the scaffold on every",
  "# update that declares a schedule, dropped by _drop_app_cron when one is",
  "# removed). It must NOT be tracked: tracking it lets a later merge-abort or",
  "# conflict hard-reset restore a dropped script, which the entrypoint boot",
  "# replay then re-arms as an orphan cron (card 099).",
  "init-cron.sh",
  "# Defensive: the integer-id storage tree is a sibling dir, but if a",
  "# numeric data dir ever lands here it is runtime data, not source.",
  "[0-9]*/",
  "",
])

# A fixed identity so commits don't depend on the container's global git
# config (which the mobius user may not have set). The installer commits
# under the upstream identity; local commits keep the same identity since
# the agent is the de-facto author of every local edit.
_GIT_NAME = "Mobius"
_GIT_EMAIL = "mobius@localhost"

# Subprocess timeout. App repos are tiny (one source file plus a couple
# of scripts), so any git op that runs longer than this is wedged, not
# slow.
_GIT_TIMEOUT = 30


@dataclass
class MergeResult:
  """Verdict of merging `upstream` into the local `main` branch.

  `status` is 'clean' when the three-way merge produced no conflicts and
  `merged_tree_oid` is the oid of the full merged tree; the caller passes it to
  `read_merged_tree` to materialise EVERY merged file and writes the whole tree
  back. `status` is 'conflict' when at least one tracked file conflicted;
  `conflict_paths` names them and `merged_tree_oid` is None — the caller must NOT
  write anything, leaving the local edits intact for an agent to resolve.

  There is one path for one and many files: a single-file app is just a tree
  with one source key (`index.jsx`), so the caller always reads the merged tree
  rather than a single-entry shortcut.
  """
  status: str
  conflict_paths: list[str] = field(default_factory=list)
  merged_tree_oid: str | None = None


def _git_env(repo: Path | str) -> dict:
  """Isolated env for a per-app git op so it can never bleed into an
  enclosing repo. `/data` is itself a git repo (the agent's pm-commit
  history), so a source_dir with no dedicated `.git` would otherwise let
  git walk up to `/data` — making every per-app op operate on the wrong
  repo and report spurious conflicts. Pin GIT_CEILING_DIRECTORIES to the
  app-dir's parent (git won't search above it → it finds the app's OWN
  repo or none, never /data) and scrub inherited GIT_* pointers that would
  override `-C`. Used by EVERY git subprocess here (`_run` + the few direct
  bytes-on-stdin calls). Mirrors the test conftest's `_isolate_git_env`.
  """
  env = dict(os.environ)
  for var in (
    "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE",
    "GIT_OBJECT_DIRECTORY", "GIT_COMMON_DIR", "GIT_NAMESPACE",
  ):
    env.pop(var, None)
  env["GIT_CEILING_DIRECTORIES"] = str(Path(repo).resolve().parent)
  return env


def _run(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
  """Runs `git -C <repo> <args>` with the fixed Mobius identity.

  The identity is injected per-invocation via `-c` rather than written
  into the repo config so the repo carries no state the next reader has
  to know about. `check=False` lets callers inspect a non-zero return
  (e.g. merge-tree signalling a conflict) instead of raising. Runs under
  the isolated `_git_env` so it can never bleed into the enclosing /data
  repo.
  """
  cmd = [
    "git",
    "-c", f"user.name={_GIT_NAME}",
    "-c", f"user.email={_GIT_EMAIL}",
    "-C", str(repo),
    *args,
  ]
  return subprocess.run(
    cmd, capture_output=True, text=True, timeout=_GIT_TIMEOUT,
    check=check, env=_git_env(repo),
  )


def _tracked_source(source_dir: Path) -> list[str]:
  """The source files to stage: everything in the dir minus what
  `.gitignore` excludes. We add by directory (`git add -A`) and let the
  committed `.gitignore` do the filtering, so a new job script the agent
  drops in is picked up without this module enumerating extensions."""
  return ["-A"]


def is_repo(source_dir: str | Path) -> bool:
  """Whether `source_dir` already holds a git repo."""
  return (Path(source_dir) / ".git").exists()


def head_sha(source_dir: str | Path, branch: str) -> str:
  """The commit sha at the tip of `branch` (e.g. the merge base an
  update will diverge from). Assumes the repo + branch exist."""
  return _run(Path(source_dir), "rev-parse", branch).stdout.strip()


def has_origin(source_dir: str | Path) -> bool:
  """Whether this app repo has a real `origin` remote.

  A cloned catalog app has `origin`; a synthetic-upstream app created via
  `record_upstream` does not. Treat any git failure as false so callers can
  fall back to the synthetic path unchanged.
  """
  if not is_repo(source_dir):
    return False
  proc = _run(
    Path(source_dir), "remote", "get-url", "origin", check=False,
  )
  return proc.returncode == 0


def clone_upstream(
  source_dir: str | Path, repo_url: str, ref: str, *, depth: int = 1,
) -> str:
  """Clone a real upstream repo and check out local `main` at `origin/<ref>`.

  This is the REAL-origin install variant of `record_upstream`: instead of
  synthesizing an installer-owned `upstream` branch from fetched bytes, it keeps
  the app repository's own origin and makes `origin/<ref>` the pristine
  upstream. That remote-tracking commit is a real catalog commit an update can
  fetch from and a local fix can be pushed against as a PR. Local edits then
  commit onto `main`, so `git diff origin/<ref> main` is the user's delta.

  `source_dir` may already exist as an empty directory. The clone is built in a
  sibling temp directory first and moved into place after success, so a failed
  clone leaves the caller free to fall back to the synthetic `record_upstream`
  path without a half-created `.git`.

  Returns:
    The checked-out HEAD sha.
  """
  repo = Path(source_dir)
  if repo.exists() and not repo.is_dir():
    raise RuntimeError(f"source_dir exists and is not a directory: {repo}")
  repo.parent.mkdir(parents=True, exist_ok=True)
  clone_parent = repo.parent
  with tempfile.TemporaryDirectory(
    prefix=f".{repo.name}.clone-", dir=clone_parent,
  ) as tmp:
    clone_dir = Path(tmp) / "repo"
    cmd = [
      "git",
      "-c", f"user.name={_GIT_NAME}",
      "-c", f"user.email={_GIT_EMAIL}",
      # core.symlinks=false: check out any tracked symlink as a PLAIN FILE
      # (the link text as content), never a real filesystem symlink. Catalog
      # repos are untrusted content; a materialized symlink (e.g. `static` ->
      # outside the app dir, or `index.jsx` -> /data/service-token.txt) would
      # escape the containment the fetched-source path enforces via
      # _assert_within — that guard is skipped for the cloned tree, so the
      # non-symlink checkout is what keeps the clone inside its own dir.
      "-c", "core.symlinks=false",
      "clone", "-q",
      "--depth", str(depth),
      "--branch", ref,
      repo_url,
      str(clone_dir),
    ]
    subprocess.run(
      cmd, capture_output=True, text=True, timeout=_GIT_TIMEOUT,
      check=True, env=_git_env(repo),
    )
    remote_ref = f"origin/{ref}"
    _run(clone_dir, "rev-parse", "--verify", remote_ref)
    _run(clone_dir, "branch", "-f", UPSTREAM_BRANCH, remote_ref)
    _run(clone_dir, "checkout", "-q", "-B", LOCAL_BRANCH, remote_ref)
    # Keep the app's OWN .gitignore committed (it travels upstream), but layer
    # Möbius's managed-artifact ignores locally via .git/info/exclude so a
    # later `git add -A` never tracks generated per-install files (static/,
    # the static-asset manifest, init-cron.sh, *.bak, the compiled/id trees).
    # A committed catalog .gitignore rarely lists these; without this, the
    # first commit pollutes `main` and — since record_upstream preserves the
    # on-disk .gitignore — never self-heals (the card-099 orphan-cron class).
    exclude = clone_dir / ".git" / "info" / "exclude"
    exclude.parent.mkdir(parents=True, exist_ok=True)
    exclude.write_text(_GITIGNORE + "\n", encoding="utf-8")
    sha = _run(clone_dir, "rev-parse", "HEAD").stdout.strip()
    repo.mkdir(parents=True, exist_ok=True)
    existing = list(repo.iterdir())
    if existing:
      raise RuntimeError(f"source_dir is not empty: {repo}")
    for child in clone_dir.iterdir():
      shutil.move(str(child), str(repo / child.name))
    return sha


def fetch_upstream(source_dir: str | Path, ref: str) -> str:
  """Fetch `origin/<ref>` and advance local `upstream` to that real commit.

  This is the cloned-app update analogue of `record_upstream`: the catalog's
  complete git tree is fetched from the real remote, then the installer-owned
  `upstream` branch is moved to the fetched remote-tracking commit.
  Depth-1 fetches can leave the previous upstream behind a shallow boundary;
  when that happens, unshallow so Git can prove ancestry and the existing merge
  path can compute a real merge base.

  Returns:
    The fetched `origin/<ref>` commit sha.
  """
  repo = Path(source_dir)
  previous = _run(
    repo, "rev-parse", "--verify", UPSTREAM_BRANCH, check=False,
  )
  previous_sha = previous.stdout.strip() if previous.returncode == 0 else ""
  _run(repo, "fetch", "--depth", "1", "origin", ref)
  remote_ref = f"origin/{ref}"
  sha = _run(repo, "rev-parse", "--verify", remote_ref).stdout.strip()
  if previous_sha and previous_sha != sha:
    related = _run(
      repo, "merge-base", "--is-ancestor", previous_sha, sha, check=False,
    )
    if related.returncode != 0 and (repo / ".git" / "shallow").exists():
      _run(repo, "fetch", "--unshallow", "origin", ref)
  _run(repo, "branch", "-f", UPSTREAM_BRANCH, remote_ref)
  return sha


def ensure_repo(source_dir: str | Path) -> None:
  """Initializes the per-app repo if absent; a no-op once it exists.

  Creates the repo, writes the `.gitignore`, and makes an empty root
  commit on `upstream`. `main` is branched from that same root and
  checked out as the working branch.

  The empty root is deliberate: a meaningful merge needs `main` to
  descend from the SAME `upstream` commit that recorded the version it
  was installed at, so that a later update's merge base is the
  previously-installed version (not an unrelated root). The install path
  establishes that by `record_upstream` + `align_local_to_upstream`; the
  empty root is just the shared seed both branches grow from. Idempotent:
  re-running on an existing repo does nothing.
  """
  repo = Path(source_dir)
  if is_repo(repo):
    return
  repo.mkdir(parents=True, exist_ok=True)
  _run(repo, "init", "-q", "-b", UPSTREAM_BRANCH)
  (repo / ".gitignore").write_text(_GITIGNORE, encoding="utf-8")
  _run(repo, "add", ".gitignore")
  _run(repo, "commit", "-q", "-m", "Initialize app repo", "--allow-empty")
  _run(repo, "branch", LOCAL_BRANCH, UPSTREAM_BRANCH)
  _run(repo, "checkout", "-q", LOCAL_BRANCH)


def align_local_to_upstream(source_dir: str | Path) -> None:
  """Resets the local `main` branch to the current `upstream` tip.

  Called at INSTALL so the working branch starts at exactly the
  installed version: `main` then descends from that upstream commit, and
  the next update's three-way merge has it as the shared base. Must NOT
  be called on update — that would discard the local edits this whole
  model exists to preserve.

  Updates the branch ref and checks the working tree out to it so the
  on-disk `index.jsx` matches what was just installed.
  """
  repo = Path(source_dir)
  up = head_sha(repo, UPSTREAM_BRANCH)
  _run(repo, "checkout", "-q", LOCAL_BRANCH)
  _run(repo, "reset", "-q", "--hard", up)


def record_upstream(
  source_dir: str | Path,
  files: dict[str, bytes],
  manifest_url: str,
  version: str,
  *,
  exec_paths: frozenset[str] = frozenset(),
) -> str:
  """Commits the pristine installed SOURCE TREE onto `upstream`.

  Records the COMPLETE shipped tree `files` (repo-relative path -> bytes) onto
  the upstream branch as the canonical "this is what version <version> shipped"
  snapshot, WITHOUT disturbing the checked-out `main` working tree. Returns the
  new upstream commit sha (the merge base a later update diverges from).

  `files` is the whole tree: `index.jsx` is just one key, sibling modules
  (`cards.js`, …) are more keys, and the schedule job script is a key listed in
  `exec_paths`. There is no entry/sibling distinction — recording the whole tree
  is what lets a multi-file app update cleanly (a sibling that only ever lived on
  `main` would have no pristine `upstream` version to three-way-merge against,
  so every update would keep it stale or report a spurious add/add conflict).
  The managed `.gitignore` is always carried in regardless of `files`.

  Paths in `exec_paths` are staged executable (100755), everything else 100644;
  the caller names the exec files explicitly (no `*.sh` inference). The job
  script's mode must match what `main` records or the merge reports a phantom
  add/add conflict on a pure 644-vs-755 skew. The tree is built from an EMPTY
  index, not by patching the previous upstream tip, so a file DROPPED from the
  new version is correctly removed from `upstream` too. Staged into a temp view
  of the shared index and restored to `main` afterwards, so the live working
  tree the watcher may be compiling stays put.
  """
  repo = Path(source_dir)
  ensure_repo(repo)
  parent = _run(repo, "rev-parse", UPSTREAM_BRANCH).stdout.strip()
  # Preserve the existing managed .gitignore exactly (avoids churning it when the
  # module constant drifts); fall back to the constant if upstream lacks one.
  gi = subprocess.run(
    ["git", "-C", str(repo), "cat-file", "-p", f"{UPSTREAM_BRANCH}:.gitignore"],
    capture_output=True, timeout=_GIT_TIMEOUT, check=False, env=_git_env(repo),
  )
  gitignore_bytes = gi.stdout if gi.returncode == 0 else _GITIGNORE.encode()
  # The full pristine source set: the managed .gitignore plus every file in the
  # shipped tree. Files in `exec_paths` are 100755 so `upstream` and `main` agree
  # on the mode (a 644/755 skew alone makes merge report a phantom add/add).
  staged: list[tuple[str, bytes, str]] = [
    (".gitignore", gitignore_bytes, "100644"),
  ]
  for rel, data in files.items():
    if rel == ".gitignore":
      continue  # the managed .gitignore always wins
    staged.append((rel, data, "100755" if rel in exec_paths else "100644"))
  # Build the upstream tree from an EMPTY index so files dropped from the new
  # version vanish. Each blob needs bytes on stdin (which text-mode `_run` can't
  # carry), so hash-object + update-index run as direct subprocess calls under
  # the isolated git env.
  _run(repo, "read-tree", "--empty")
  for rel, data, mode in staged:
    blob = subprocess.run(
      ["git", "-C", str(repo), "hash-object", "-w", "--stdin", "--path", rel],
      input=data, capture_output=True, timeout=_GIT_TIMEOUT, check=True,
      env=_git_env(repo),
    ).stdout.decode().strip()
    subprocess.run(
      ["git", "-C", str(repo), "update-index", "--add", "--cacheinfo",
       f"{mode},{blob},{rel}"],
      capture_output=True, text=True, timeout=_GIT_TIMEOUT, check=True,
      env=_git_env(repo),
    )
  tree = _run(repo, "write-tree").stdout.strip()
  msg = f"install v{version} from {manifest_url}"
  sha = _run(
    repo, "commit-tree", tree, "-p", parent, "-m", msg,
  ).stdout.strip()
  _run(repo, "update-ref", f"refs/heads/{UPSTREAM_BRANCH}", sha)
  # Restore the index to match the checked-out working branch so a later
  # `git status`/commit on `main` isn't confused by the tree we just staged.
  _run(repo, "read-tree", LOCAL_BRANCH)
  return sha


def has_unresolved_conflicts(source_dir: str | Path) -> bool:
  """Whether an in-progress merge still has ANY tracked file unresolved.

  The invariant this guards: an update must NEVER finalize while conflict
  markers remain in any tracked file. Two signals, BOTH required, because
  they cover disjoint moments of the resolve flow:

  - `git ls-files -u` lists unmerged index entries. It is non-empty right
    after `start_conflict_merge` materializes the conflict, BUT it clears
    the instant the agent `git add`s a file — even one that still carries
    `<<<<<<<` markers (adding marks the path "resolved" in the index
    regardless of content).
  - A `git grep` for the LABELED boundary markers (`<<<<<<< <ref>` and
    `>>>>>>> <ref>`) still fires on a marker-bearing file the agent has
    already staged. We match only those two boundaries — NOT `git diff
    --check`, which flags any 7-char marker line including a bare `=======`.
    A legitimate `=======` separator (a heredoc divider, a setext rule) in
    resolved app content would otherwise read as an unresolved conflict
    forever and deadlock the update. The labeled boundaries that a real `git
    merge` always writes essentially never start a line of real source.

  Only meaningful while a merge is in progress: outside a merge there is
  nothing to finalize, so the caller is expected to check MERGE_HEAD first
  and this returns False (no unmerged entries, `--check` not run).
  """
  repo = Path(source_dir)
  if not (repo / ".git" / "MERGE_HEAD").exists():
    return False
  unmerged = _run(repo, "ls-files", "-u").stdout.strip()
  if unmerged:
    return True
  # Scan tracked content for the labeled conflict boundaries. `git grep`
  # exits 0 when a line matches, 1 when none do. We match only `<<<<<<< ` and
  # `>>>>>>> ` (7 chars + the space before the ref that `git merge` writes),
  # never the bare `=======` separator that `git diff --check` would flag on
  # legitimate content — see the docstring.
  markers = _run(repo, "grep", "-lE", r"^(<<<<<<< |>>>>>>> )", check=False)
  return markers.returncode == 0


def commit_local(source_dir: str | Path, msg: str) -> str | None:
  """Commits the current working-tree source onto `main`.

  Stages the source files (filtered by `.gitignore`) and commits them as
  a local edit. Returns the new commit sha, or None when there was
  nothing to commit (the tree already matches `main`'s tip) — a no-op
  rather than an empty commit so the history stays meaningful.

  HARD GATE on the merge-finalize path: if a merge is in progress
  (MERGE_HEAD present) and `has_unresolved_conflicts` is True, this REFUSES
  to commit and returns None, leaving the merge in progress. The invariant
  is that an update is never finalized while ANY tracked file still holds
  conflict markers — without this gate a conflict in a NON-entry file (a
  job script like `fetch.sh`) would sail through, because the only other
  resolution signal is "does index.jsx compile", which stays true. So no
  caller (watcher or install) can commit a marker-bearing tree as source.

  If a merge is in progress and FULLY resolved (no unmerged entries, no
  markers), this finalizes it as a SINGLE-parent replay commit parented on
  the upstream tip read from `.git/MERGE_HEAD`, so the upstream tip becomes
  a direct parent of `main` and the merge base advances for free while
  history stays linear — the same `A -> B -> X` shape `commit_replay` makes
  for a clean apply. The pre-merge local `main` tip becomes unreachable
  (its content lives on in the replay's tree); the squash is intentional.
  An ordinary local edit (no MERGE_HEAD) still commits as a plain
  single-parent commit on the old `main` tip.
  """
  repo = Path(source_dir)
  ensure_repo(repo)
  # Stage BEFORE the gate so `has_unresolved_conflicts` reads git's resolved
  # state: staging marks unmerged paths resolved in the index (clearing
  # `ls-files -u`) whether or not their content is clean, so the gate then
  # rests on the marker scan, which fires only when markers actually remain.
  # If we gated before staging, a conflict the agent resolved on disk but
  # never `git add`ed would still show as an unmerged index entry and we'd
  # wrongly refuse to finalize a clean resolution.
  _run(repo, "add", *_tracked_source(repo))
  merge_head_path = repo / ".git" / "MERGE_HEAD"
  if merge_head_path.exists():
    if has_unresolved_conflicts(repo):
      return None
    # Finalize the resolved merge as a single-parent replay on the upstream
    # tip so the line stays linear. A plain `git commit` here would parent on
    # BOTH the old main tip and MERGE_HEAD (git makes a merge commit whenever
    # MERGE_HEAD is set), fanning history into a 2-parent merge; we want the
    # squashed `A -> B -> X` shape instead, identical to commit_replay.
    merge_head = merge_head_path.read_text(encoding="utf-8").strip()
    tree = _run(repo, "write-tree").stdout.strip()
    sha = _run(
      repo, "commit-tree", tree, "-p", merge_head, "-m", msg,
    ).stdout.strip()
    _run(repo, "update-ref", f"refs/heads/{LOCAL_BRANCH}", sha)
    for name in ("MERGE_HEAD", "MERGE_MSG", "MERGE_MODE"):
      (repo / ".git" / name).unlink(missing_ok=True)
    return sha
  status = _run(repo, "status", "--porcelain").stdout.strip()
  if not status:
    return None
  _run(repo, "commit", "-q", "-m", msg)
  return _run(repo, "rev-parse", LOCAL_BRANCH).stdout.strip()


def commit_replay(
  source_dir: str | Path, upstream_tip: str, msg: str,
) -> str | None:
  """Records the working-tree source onto `main` as a single-parent replay.

  Commits the current working tree (the just-applied merge result) with a
  SINGLE parent: `upstream_tip` (the upstream commit whose changes were
  folded in). The local delta is squashed into this one replay commit on
  top of upstream, so history stays linear (`A -> B -> X`): `main` is a
  straight-line descendant of `upstream`, after which `upstream_tip` is a
  direct parent of `main` and `git merge-base --is-ancestor upstream main`
  is exact. That ancestry is what advances the base — the NEXT update's
  three-way merge diffs only the genuinely-new upstream delta against local
  edits instead of re-litigating already-merged history against a stale base
  (the bug that turned every repeated update into a spurious conflict).

  The previous local `main` tip becomes unreachable after the replay, which
  is intentional: its content lives on in the replay commit's tree, and the
  squash is what keeps the line linear rather than fanning into a merge.

  A plain `commit_local` cannot do this: it parents on the old `main` tip,
  which leaves `upstream` unreachable from `main`, so `git merge-base` keeps
  returning the original install point. Returns the new commit sha, or None
  when there is nothing to record (working tree already matches `main` and
  `upstream_tip` is already an ancestor — e.g. a re-install of the same
  version with no local edits).
  """
  repo = Path(source_dir)
  ensure_repo(repo)
  _run(repo, "add", *_tracked_source(repo))
  tree = _run(repo, "write-tree").stdout.strip()
  main_tree = _run(repo, "rev-parse", f"{LOCAL_BRANCH}^{{tree}}").stdout.strip()
  already_merged = _run(
    repo, "merge-base", "--is-ancestor", upstream_tip, LOCAL_BRANCH,
    check=False,
  ).returncode == 0
  if tree == main_tree and already_merged:
    return None
  sha = _run(
    repo, "commit-tree", tree, "-p", upstream_tip, "-m", msg,
  ).stdout.strip()
  _run(repo, "update-ref", f"refs/heads/{LOCAL_BRANCH}", sha)
  return sha


def local_diverged_from(source_dir: str | Path, base_commit: str) -> bool:
  """Whether local `main` differs from `base_commit`.

  The caller uses the previous upstream commit as `base_commit`, before
  recording a new upstream version. Exit 0 means no local tree delta;
  non-zero means local edits exist or git could not prove equality.
  """
  proc = _run(
    Path(source_dir), "diff", "--quiet", base_commit, LOCAL_BRANCH,
    check=False,
  )
  return proc.returncode != 0


def merge_upstream(source_dir: str | Path) -> MergeResult:
  """Merges `upstream` into `main` and returns the verdict.

  Uses `git merge-tree --write-tree` to perform the three-way merge in
  memory: it neither moves `main` nor touches the working tree, so a
  conflict cannot leave the app served in a half-merged state. On a clean
  merge `merged_tree_oid` is the resulting tree; the caller materialises the
  WHOLE tree via `read_merged_tree` (there is no single-file shortcut — a
  single-file app is just a tree with one source key) and writes it back. On
  conflict the conflicting paths are returned and `merged_tree_oid` is None —
  the caller leaves the local edits untouched.

  The caller is responsible for advancing `main` to the merged tree (by
  writing it and letting the watcher/`commit_local` commit it). We deliberately
  do NOT fast-forward `main` here: the merged source has to be recompiled and
  committed as one transactional unit on the caller's side, and moving the
  branch before that would briefly point `main` at a tree the compiled bundle
  doesn't match.
  """
  repo = Path(source_dir)
  ensure_repo(repo)
  proc = _run(
    repo, "merge-tree", "--write-tree", "--name-only",
    LOCAL_BRANCH, UPSTREAM_BRANCH,
    check=False,
  )
  # merge-tree exits 0 on a clean merge, 1 on conflicts, >1 on real
  # errors. stdout's first line is always the merged tree oid. On a
  # conflict the `--name-only` section follows: the conflicting file
  # paths are the lines AFTER the oid up to the first blank line; the
  # lines after that blank are human-readable "CONFLICT (...)" messages,
  # not paths.
  if proc.returncode > 1:
    raise RuntimeError(
      f"git merge-tree failed (rc={proc.returncode}): {proc.stderr.strip()}"
    )
  lines = proc.stdout.splitlines()
  tree_oid = lines[0].strip() if lines else ""
  if proc.returncode == 1:
    conflict_paths: list[str] = []
    for ln in lines[1:]:
      if not ln.strip():
        break  # blank line ends the path section
      conflict_paths.append(ln.strip())
    return MergeResult(status="conflict", conflict_paths=conflict_paths)
  return MergeResult(status="clean", merged_tree_oid=tree_oid)


def read_merged_tree(source_dir: str | Path, tree_oid: str) -> dict[str, bytes]:
  """Read EVERY file of a merged tree oid into {repo_relative_path: bytes}.

  The single source-tree path: every clean-merge caller (app install + the
  platform layer) materialises the WHOLE merged tree from
  `MergeResult.merged_tree_oid` here and writes it back, so one and many files
  share one path. Paths are repo-relative POSIX; bytes are read binary-faithful
  (no text decode). `-z` keeps paths NUL-separated so names with spaces or
  newlines survive.
  """
  repo = Path(source_dir)
  listing = subprocess.run(
    ["git", "-C", str(repo), "ls-tree", "-r", "-z", "--name-only", tree_oid],
    capture_output=True, timeout=_GIT_TIMEOUT, check=True, env=_git_env(repo),
  )
  files: dict[str, bytes] = {}
  for rel in listing.stdout.decode().split("\0"):
    if not rel:
      continue
    blob = subprocess.run(
      ["git", "-C", str(repo), "cat-file", "-p", f"{tree_oid}:{rel}"],
      capture_output=True, timeout=_GIT_TIMEOUT, check=False, env=_git_env(repo),
    )
    if blob.returncode == 0:
      files[rel] = blob.stdout
  return files


def read_ref_tree(source_dir: str | Path, ref: str) -> dict[str, bytes]:
  """Read EVERY file at `ref` into {repo_relative_path: bytes}.

  `ref` may be a branch, tag, or commit. It is resolved to its tree first so
  callers share the same binary-faithful full-tree reader as clean merges.
  """
  repo = Path(source_dir)
  tree_oid = _run(repo, "rev-parse", f"{ref}^{{tree}}").stdout.strip()
  return read_merged_tree(repo, tree_oid)


def start_conflict_merge(source_dir: str | Path) -> list[str]:
  """Starts a REAL merge of `upstream` into the working tree on `main`.

  Unlike `merge_upstream` (an in-memory verdict that never touches the tree),
  this MUTATES the working tree: `git merge --no-commit --no-ff upstream`
  writes conflict markers into the conflicting files and records `MERGE_HEAD`,
  leaving exactly the state a human's `git pull` would — so the agent resolves
  it with ordinary git. The caller must NOT recompile afterward: the
  marker-bearing source won't compile, so the file watcher keeps serving the
  prior good bundle until the agent resolves the markers and finishes the merge
  (`git add` + `git commit` / `git merge --continue`), at which point
  `commit_local` finalizes a single-parent replay (linear) on the upstream
  tip and the base advances.

  To back out, the agent runs `git merge --abort`, restoring `main` to its
  pre-merge (committed local) state. Call only after `merge_upstream` verdicted
  a conflict, and under `source_dir_lock`.

  Returns the conflicting repo-relative paths. In the pathological case where
  the real merge resolves clean (it shares ort machinery with `merge_upstream`,
  so they agree in practice), the in-progress merge is aborted and an empty list
  is returned so the caller never strands a half-merge.
  """
  repo = Path(source_dir)
  ensure_repo(repo)
  _run(repo, "merge", "--no-commit", "--no-ff", UPSTREAM_BRANCH, check=False)
  # Unmerged paths show in `git status --porcelain` with a U in either status
  # column (UU/AU/UA/UD/DU) or the AA/DD both-added/both-deleted codes.
  status = _run(repo, "status", "--porcelain").stdout
  conflict_paths: list[str] = []
  for line in status.splitlines():
    xy = line[:2]
    if "U" in xy or xy in ("AA", "DD"):
      conflict_paths.append(line[3:].strip())
  if not conflict_paths and (repo / ".git" / "MERGE_HEAD").exists():
    # Real merge resolved clean (vs the conflict verdict). Don't strand a
    # dangling --no-commit merge; abort back to the committed local state.
    _run(repo, "merge", "--abort", check=False)
  return conflict_paths


def abort_in_progress_merge(source_dir: str | Path) -> bool:
  """Abort a half-finished merge left by a prior unresolved conflict.

  When a `start_conflict_merge` was never resolved (MERGE_HEAD still set,
  markers on disk) and a NEW update arrives, the caller must abort the stale
  merge before committing local edits — otherwise the markers get committed as
  source. `git merge --abort` restores `main`'s working tree to its pre-merge
  (committed local) state. Returns True if a merge was aborted, else False.
  """
  repo = Path(source_dir)
  if not is_repo(repo) or not (repo / ".git" / "MERGE_HEAD").exists():
    return False
  _run(repo, "merge", "--abort", check=False)
  return True


# Smells
# - record_upstream stages the new blob into the SHARED index (read-tree
#   upstream -> update-index -> write-tree) then read-tree's it back to
#   `main`. That borrows the working index for a write-tree, which is safe
#   only because the caller holds source_dir_lock so the watcher can't be
#   committing on `main` concurrently. The lock contract is documented at
#   the module top; flagged here because the index-borrow is the spot that
#   relies on it. A conflict-free alternative is a bare temp index
#   (GIT_INDEX_FILE), deferred until a non-locked caller needs it.
# - The whole source tree flows through record_upstream + merge_upstream as one
#   set: record_upstream commits every file in `files` onto the `upstream` tree
#   (the schedule job script is just a key listed in `exec_paths`), and a clean
#   merge_upstream hands back the merged tree oid the caller reads in full via
#   read_merged_tree. A locally edited fetch.sh/build.sh survives a clean update
#   like any other file — there is no entry/sibling/job special-casing.
