"""Install-managed paths and their distinct Git/installer policies.

Ignore rules prevent new runtime files from entering app history. Untrack
pathspecs also remove legacy tracked files from the index, while merged-tree
drops exclude exact installer-owned names from source writes. These policies
have intentionally different memberships; declare each path's roles together
rather than inferring one policy from another.
"""

from __future__ import annotations

from dataclasses import dataclass

STATIC_ASSETS_MANIFEST = ".mobius-static-assets.json"


@dataclass(frozen=True)
class ManagedPath:
  """One path or group with explicit policy roles.

  Ignore lines include comments and use gitignore syntax. Untrack selectors
  use Git pathspec syntax; their order is irrelevant. Entries dropped from
  installer source handling use an exact tree key as their name.
  """

  name: str
  ignore_lines: tuple[str, ...] = ()
  untrack_pathspecs: tuple[str, ...] = ()
  drop_from_merged_tree: bool = False


# Order preserves the generated ignore file; entries without ignore lines
# participate only in untracking or merged-tree filtering.
REGISTRY: tuple[ManagedPath, ...] = (
  # Tracked but install-managed: excluded from source handling, no ignore line.
  ManagedPath(name=".gitignore", drop_from_merged_tree=True),
  ManagedPath(
    name="build-output",
    ignore_lines=(
      "# Generated build output and vendored deps are not hand-written source.",
      "dist/",
      ".build/",
      "node_modules/",
    ),
  ),
  ManagedPath(
    name="python-cache",
    ignore_lines=(
      "# Python app jobs compile beside source; bytecode is runtime cache, not source.",
      "__pycache__/",
      "*.py[cod]",
      ".pytest_cache/",
      ".mypy_cache/",
      ".ruff_cache/",
      ".coverage",
      "htmlcov/",
    ),
    untrack_pathspecs=(
      ":(glob)**/__pycache__/**",
      ":(glob)**/*.py[cod]",
      ":(glob)**/.pytest_cache/**",
      ":(glob)**/.mypy_cache/**",
      ":(glob)**/.ruff_cache/**",
      ":(glob)**/.coverage",
      ":(glob)**/htmlcov/**",
    ),
  ),
  ManagedPath(
    name="diagnostics",
    ignore_lines=(
      "# Local diagnostics, editor residue, and machine-specific secrets are not source.",
      "*.log",
      ".DS_Store",
      "*.swp",
      "*.swo",
      "*~",
      ".env",
      ".env.local",
      ".env.*.local",
      ".build-*/",
    ),
    untrack_pathspecs=(
      ":(glob)**/*.log",
      ":(glob)**/.DS_Store",
      ":(glob)**/*.swp",
      ":(glob)**/*.swo",
      ":(glob)**/*~",
      ":(glob)**/.env",
      ":(glob)**/.env.local",
      ":(glob)**/.env.*.local",
      ":(glob)**/.build-*/**",
    ),
  ),
  ManagedPath(
    name="static-subtree",
    ignore_lines=(
      "# Manifest static_assets are install-managed (re-fetched from the manifest,",
      "# tracked in .mobius-static-assets.json), not edited source — keep runtime",
      "# bundles/binaries out of history while admitting Store listing media through",
      "# the one author-owned subtree reserved by the manifest contract.",
      "static/*",
      "!static/store/",
      "!static/store/**",
    ),
  ),
  ManagedPath(
    name=STATIC_ASSETS_MANIFEST,
    ignore_lines=(STATIC_ASSETS_MANIFEST,),
    untrack_pathspecs=(STATIC_ASSETS_MANIFEST,),
    drop_from_merged_tree=True,
  ),
  ManagedPath(
    name="install-snapshots",
    ignore_lines=(
      "# Install/rollback snapshots are not source.",
      "*.bak",
      "*.mobius-bak",
      "*.mobius-drop-bak",
    ),
    untrack_pathspecs=(
      "*.bak",
      "*.mobius-bak",
      "*.mobius-drop-bak",
      ":(glob)**/*.bak",
      ":(glob)**/*.mobius-bak",
      ":(glob)**/*.mobius-drop-bak",
    ),
  ),
  ManagedPath(
    name="init-cron.sh",
    ignore_lines=(
      "# init-cron.sh is install-managed (re-generated by the scaffold on every",
      "# update that declares a schedule, dropped by _drop_app_cron when one is",
      "# removed). It must NOT be tracked: tracking it lets a later merge-abort or",
      "# conflict hard-reset restore a dropped script, which the entrypoint boot",
      "# replay then re-arms as an orphan cron.",
      "init-cron.sh",
    ),
    untrack_pathspecs=("init-cron.sh",),
    drop_from_merged_tree=True,
  ),
  ManagedPath(
    name="init-cron.sh.tombstoned",
    ignore_lines=("init-cron.sh.tombstoned",),
    untrack_pathspecs=("init-cron.sh.tombstoned",),
  ),
  ManagedPath(
    name=".cron-pending.json",
    ignore_lines=(".cron-pending.json",),
    untrack_pathspecs=(".cron-pending.json",),
  ),
  ManagedPath(
    name="runtime-workspaces",
    ignore_lines=(
      "# Runtime workspaces staged by scheduled/background apps are not source.",
      "inputs/",
      "runs/",
    ),
    untrack_pathspecs=("inputs", "runs"),
  ),
  ManagedPath(
    name="settings.json",
    ignore_lines=("settings.json",),
    untrack_pathspecs=("settings.json",),
  ),
  ManagedPath(
    name="last-run.json",
    ignore_lines=("last-run.json",),
    untrack_pathspecs=("last-run.json",),
  ),
  ManagedPath(
    name="reflection-brief-template.html",
    ignore_lines=("reflection-brief-template.html",),
    untrack_pathspecs=("reflection-brief-template.html",),
  ),
  ManagedPath(
    name="fork-chat.sh",
    ignore_lines=("fork-chat.sh",),
    untrack_pathspecs=("fork-chat.sh",),
  ),
  ManagedPath(
    name="fork-session.sh",
    ignore_lines=("fork-session.sh",),
    untrack_pathspecs=("fork-session.sh",),
  ),
  ManagedPath(
    name="numeric-storage",
    ignore_lines=(
      "# Defensive: the integer-id storage tree is a sibling dir, but if a",
      "# numeric data dir ever lands here it is runtime data, not source.",
      "[0-9]*/",
    ),
  ),
)


# Derived views. Import these instead of maintaining parallel policies.
GITIGNORE = "\n".join(line for entry in REGISTRY for line in entry.ignore_lines) + "\n"
MANAGED_RUNTIME_PATHS = tuple(
  spec for entry in REGISTRY for spec in entry.untrack_pathspecs
)
MERGED_NON_SOURCE = frozenset(
  entry.name for entry in REGISTRY if entry.drop_from_merged_tree
)
